name: fetch_prices
on:
  schedule:
    - cron: '0 13 * * 1-5'   # 平日 22:00 JST（UTC 13:00）
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - name: Run price fetcher
        run: python scripts/get_prices.py
      - name: Commit CSV
        run: |
          git config user.name bot
          git config user.email bot@example.com
          git add data/*.csv
          git commit -m "auto: update prices" || echo "no change"
          git push
